### PR TITLE
Add laravel 5.8.x-dev for testing

### PR DESCRIPTION
**Pull request by daison12006013**
CI Testing.

---

#### Proposal
**Branch:** 0.3
**Tag:** 0.3.0
**Laravel Framework Support:** 5.8

### CODE REVIEW

**Comment by mtrl** [comment]
Is it possible to get this pull request merged into the repo? Laravel 5.8 is now a stable release.

**Comment by daison12006013** [comment]
@mtrl I need to revert back the things I removed inside composer and also the CI

Will try another run so that it is backward compatible, or else the owner of this package needs to separate the tag version into major increment to separate laravel 5.8

**Comment by OliveIT** [comment]
When will this be merged?

**Comment by douglasresendemaciel** [comment]
Hello mate, this PR will be accepted?

**Comment by austinheap** [comment]
[v0.2.1](https://github.com/austinheap/laravel-database-encryption/releases/tag/v0.2.1) released with support for Laravel 5.8.x.

**Pull request closed without merging**
