### PR TITLE
Adds support to Laravel 5.7

### PR DESCRIPTION
**Pull request by ben182**

### CODE REVIEW

**Comment by ben182** [comment]
#28 fix

**Comment by axelitus** [comment]
The tests are failing but I don't think is related. The tests fail in this line:
https://github.com/austinheap/laravel-database-encryption/blob/b5f9b05e33bda5b11554dd4d67f18c101df191b9/tests/Traits/DatabaseTest.php#L69

No other test fails, so this "should" be safe to merge.

**Comment by jasonlbeggs** [comment]
Any update on when this will be fixed/merged? I am working on upgrading an app to Laravel 5.7.

**Comment by austinheap** [comment]
No promises on when I'll have time to dig into why the tests are failing but you can [override the `composer.json` dependency with your own branch](https://www.laurencegellert.com/2017/12/how-to-override-a-composer-dependency-so-it-pulls-from-your-branch/).

**Comment by axelitus** [comment]
Hopefully, you get the time to revise the code soon though ;)

**Comment by austinheap** [comment]
Closing in place of https://github.com/austinheap/laravel-database-encryption/commit/573112a53089d7b946005b6f65385bfebbb07138. Feedback please! 😁

**Pull request closed without merging**
